import {Telegraf,Markup} from 'telegraf'; import axios from 'axios';
const token=process.env.BOT_TOKEN;if(!token)throw new Error('BOT_TOKEN missing');const bot=new Telegraf(token);const api=process.env.API_URL||'http://localhost:4000';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));async function typing(ctx:any,ms=600){await ctx.sendChatAction('typing');await sleep(ms)}
async function channels(){try{return (await axios.get(`${api}/force-join`)).data.filter((x:any)=>x.status==='ACTIVE'&&x.required)}catch{return []}}
async function joined(ctx:any){const cs=await channels();for(const c of cs){try{const m=await ctx.telegram.getChatMember(String(c.channelId),ctx.from.id);if(!['member','administrator','creator'].includes(m.status))return false}catch{return false}}return true}
async function claim(ctx:any,code:string){if(!(await joined(ctx))){const cs=await channels();const buttons=cs.map((c:any)=>[Markup.button.url(`📢 Join ${c.title||c.username||'Channel'}`,c.username?`https://t.me/${String(c.username).replace(/^@/,'')}`:`https://t.me/c/${String(c.channelId).replace('-100','')}`)]);buttons.push([Markup.button.callback('✅ Check Membership','check_membership')]);await ctx.reply('📢 Please join all required channels first.',Markup.inlineKeyboard(buttons));return}await typing(ctx,900);try{const r=await axios.post(`${api}/qr/${code}/claim`,{telegramId:ctx.from.id,username:ctx.from.username});await ctx.reply(`⏳ Claim submitted!\n\n🎟 ${code}\n💰 Reward: pending\n📌 Status: ${r.data.status}`)}catch(e:any){const msg=e?.response?.data?.error||e?.message||'QR unavailable';await ctx.reply(msg==='QR_ALREADY_CLAIMED'?'❌ QR already claimed by another user.':msg==='QR_EXPIRED'?'⏰ This QR has expired.':`❌ Claim failed.`)}}
bot.start(async ctx=>{await typing(ctx);await ctx.reply('🎁 Welcome to QR Claim Bot!\n\nClaim one-time QR rewards, track your balance and request withdrawals.',Markup.inlineKeyboard([[Markup.button.callback('🎟 How to Claim','claim_help')],[Markup.button.callback('💰 Balance','balance')]]))});
bot.action('claim_help',async ctx=>{await ctx.answerCbQuery();await typing(ctx);await ctx.reply('🎟 Send the QR code, e.g. QR-AB12CD')});
bot.action('check_membership',async ctx=>{await ctx.answerCbQuery();if(await joined(ctx))await ctx.reply('✅ Membership verified. Now send your QR code.');else await ctx.reply('❌ You still need to join all required channels.')});
bot.action('balance',async ctx=>{await ctx.answerCbQuery();await typing(ctx,400);try{const u=(await axios.get(`${api}/users/${ctx.from!.id}/balance`)).data;await ctx.reply(`💰 Balance\n\n$${Number(u.balanceUsd||0).toFixed(2)}`)}catch{await ctx.reply('⚠️ Balance unavailable.')}});
bot.hears(/^QR-[A-Z0-9]+$/i,ctx=>claim(ctx,ctx.message.text.trim().toUpperCase()));
bot.on('text',async ctx=>{if(ctx.message.text.startsWith('/'))return;await typing(ctx,300);await ctx.reply('Send a valid QR code like QR-AB12CD.')});
async function pollNotifications(){try{const rows=(await axios.get(`${api}/internal/notifications`,{headers:{'x-bot-key':process.env.BOT_INTERNAL_KEY||''}})).data;for(const n of rows){try{await bot.telegram.sendMessage(n.telegramId,n.message);await axios.post(`${api}/notifications/${n.id}/sent`)}catch{}}}catch{}}
setInterval(pollNotifications,5000);
bot.launch();process.once('SIGINT',()=>bot.stop('SIGINT'));process.once('SIGTERM',()=>bot.stop('SIGTERM'));
