"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000";
export default function Page(){const [d,setD]=useState<any>();const [logs,setLogs]=useState<any[]>([]);const [ws,setWs]=useState<any[]>([]);const [token,setToken]=useState("");const [err,setErr]=useState("");
async function load(t=token){try{const h={Authorization:`Bearer ${t}`};const [a,b,c]=await Promise.all([fetch(`${API}/dashboard`,{headers:h}),fetch(`${API}/logs`,{headers:h}),fetch(`${API}/withdrawals`,{headers:h})]);if(!a.ok)throw new Error("Login required");setD(await a.json());setLogs(await b.json());setWs(await c.json())}catch(e:any){setErr(e.message)}}
async function review(id:string,status:"PAID"|"REJECTED"){const note=status==="REJECTED"?prompt("Rejection reason?")||"Rejected by admin":"Manual payment sent externally";const r=await fetch(`${API}/withdrawals/${id}/review`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({status,note})});if(r.ok)load();else alert("Action failed")}
useEffect(()=>{const t=localStorage.getItem("token")||"";setToken(t);if(t)load(t)},[]);
if(!token||err==="Login required")return <main className="main"><div className="panel"><h1>QR Claim Admin</h1><p>Authenticate against the API and save the returned JWT as <code>token</code> in localStorage.</p></div></main>;
return <div className="shell"><aside className="side"><div className="brand">🎟 QR Claim</div><nav className="nav">{["Dashboard","Users","QR Codes","Claims","Rewards","Withdrawals","Force Join","Logs","Admins","Settings"].map(x=><button key={x}>{x}</button>)}</nav></aside><main className="main"><div className="top"><div><h1>Dashboard</h1><div className="label">QR rewards & manual withdrawals</div></div><button onClick={()=>load()}>↻ Refresh</button></div><div className="grid">{[["Users",d?.users],["Claims",d?.claims],["Pending Rewards",d?.pendingRewards],["Pending Withdrawals",d?.pendingWithdrawals],["Active QR",d?.activeQR]].map(([a,b])=><div className="card" key={String(a)}><div className="label">{a}</div><div className="value">{b??"—"}</div></div>)}</div>
<section className="panel"><h2>💸 Manual withdrawals</h2><p className="label">You pay the user externally. Only click <b>Mark Paid</b> after the payment is actually sent.</p>{ws.filter(x=>x.status==="PENDING").map(x=><div className="row" key={x.id}><span><b>{x.id}</b> · {x.user} · ${Number(x.amountUsd).toFixed(2)} · {x.method}</span><span><button onClick={()=>review(x.id,"PAID")}>💸 Mark Paid</button> <button onClick={()=>review(x.id,"REJECTED")}>❌ Reject</button></span></div>)}{!ws.some(x=>x.status==="PENDING")&&<div className="label">No pending withdrawals.</div>}</section>
<section className="panel"><h2>Recent audit logs</h2>{logs.slice(0,12).map(x=><div className="row" key={x.id}><span>{x.action} · {x.targetType} {x.targetId||""}</span><span className="pill">{new Date(x.createdAt).toLocaleString()}</span></div>)}</section></main></div>}
